#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ZERO 2 ONE — portfolio listing generator
========================================

Writes the body of /work/index.html from tools/portfolio_data.py.
The homepage's original selected-work teaser is maintained in index.html;
this generator deliberately does not read or write that homepage section.
Arabic counterparts are generated by tools/build_ar.py.

Usage: python3 tools/build_portfolio.py [--check]
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from portfolio_data import (  # noqa: E402
    ITEMS, VIDEO_LIBRARY_URL, WHATSAPP_URL, gallery, strings_block,
    used_categories, validate,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------- the copy
WORK_H1 = "Our work"
WORK_LEAD = "From an idea to a presence worth noticing."
WORK_NOTE = ("Brand identities, creative content, search engine optimisation and advertising "
             "campaigns &mdash; in Saudi Arabia, Egypt, Kuwait and the UAE.")
WORK_FILTER_HEADING = "Filter the collection"
WORK_ALL = "All work"
WORK_CTA_TITLE = "Your next project starts with a conversation."
WORK_CTA_BODY = ("Tell us what you are building and what you need it to do. We will tell you "
                 "what we would actually start with.")
WORK_CTA_LABEL = "Tell us about your project"
VIDEO_LABEL = "View video library"
VIDEO_NOTE = "Opens a shared Google Drive folder in a new tab."
VIEW_PROJECT = "View project"
VIEW_IMAGE = "View the full-size image"


def esc_attr(text):
    """ينظّف نصّاً مُعدًّا للعرض كي يصلح داخل سمة."""
    return text.replace("&", "&amp;").replace('"', "&quot;")


def img_tag(src, w, h, alt, fit, eager=False, sizes=None, cls="z2o-card-img"):
    prio = ('fetchpriority="high" decoding="async"' if eager
            else 'decoding="async" fetchpriority="low" loading="lazy"')
    sz = f' sizes="{sizes}"' if sizes else ""
    return (f'<img class="{cls}" {prio} src="/assets/images/{src}.webp" '
            f'width="{w}" height="{h}" alt="{alt}"{sz} data-fit="{fit}" />')


def metrics_block(item, pad):
    """أرقام البطاقة — نفس بنية لوحة صفحة المشروع.

    <bdi> حول كل قيمة: في الصفحة العربية تبقى «SAR 17.6K» و«3.60×» بترتيبها
    اللاتيني، ولا ينقلب سهم «قبل ← بعد» على القارئ.
    """
    o = [f'{pad}<dl class="z2o-metrics">']
    for label, before, after in item["metrics"]:
        o += [f'{pad}   <div class="z2o-metric">',
              f'{pad}      <dt class="z2o-metric-label">{label}</dt>',
              f'{pad}      <dd class="z2o-metric-value">']
        if before is not None:
            o += [f'{pad}         <bdi class="z2o-metric-before">{before}</bdi>',
                  f'{pad}         <span class="z2o-metric-arrow" aria-hidden="true">&rarr;</span>']
        o += [f'{pad}         <bdi class="z2o-metric-after">{after}</bdi>',
              f'{pad}      </dd>',
              f'{pad}   </div>']
    o.append(f'{pad}</dl>')
    if item.get("metric_note"):
        o.append(f'{pad}<p class="z2o-metrics-note">{item["metric_note"]}</p>')
    return o


def shots_block(item, pad):
    """اللقطات التي يفتحها العارض، كعناصر حقيقية مخفيّة لا JSON.

    السبب: `build_ar.py` يتخطّى محتوى <script>، فأي تعليق داخل JSON كان سيبقى
    إنجليزيًّا في الصفحة العربية بلا أن يشتكي أحد. هنا النصّ عقدة نصّية
    و`alt` سمة مترجَمة، فيتبعان القاموس كبقية الصفحة.

    `loading="lazy"` مقصود: العنصر المخفيّ لا يُنزَّل حتى يفتحه الزائر.
    """
    shots = item.get("gallery") or []
    if not shots:
        return []
    o = [f'{pad}<div class="z2o-card-shots" hidden data-z2o-shots>']
    for g in shots:
        o += [f'{pad}   <figure>',
              f'{pad}      <img decoding="async" loading="lazy" '
              f'src="/assets/images/{g["src"]}.webp" width="{g["w"]}" height="{g["h"]}" '
              f'alt="{g["alt"]}" />',
              f'{pad}      <figcaption>{g["caption"]}</figcaption>',
              f'{pad}   </figure>']
    o.append(f'{pad}</div>')
    return o


def card(item, pad="                  ", eager=False):
    """بطاقة مشروع واحدة.

    رابط واحد فقط في كل بطاقة: عنوان المشروع. تغطية البطاقة كلها تتم بـ
    ‎`.z2o-card-link::after`‎ في CSS، فتبقى المنطقة القابلة للنقر كبيرة بلا
    رابطٍ ثانٍ يكرّر نفسه في شجرة الوصول ولا رابط داخل رابط.
    """
    to_case = bool(item.get("case"))
    shots = item.get("gallery") or []
    if to_case:
        href, extra, cue = f'/work/{item["slug"]}/', "", VIEW_PROJECT
    elif shots:
        # بلا جافاسكربت يفتح هذا الرابط الصورة نفسها بحجمها الكامل؛ ومع
        # جافاسكربت يعترضه العارض. لا زرّ معطّل في أي من الحالتين.
        #
        # data-barba-prevent ضروريّ لا تحسينيّ: barba يلتقط نقرات الروابط
        # قبل معالِجنا وينتقل بنفسه، فيفتح ملف .webp كأنه صفحة مهما
        # استدعينا preventDefault بعده. الاستثناء يعيد النقرة إلى سلوك
        # المتصفّح العاديّ — وهو ما يلغيه العارض، أو يفتح الصورة إن غاب.
        href, extra, cue = (f'/assets/images/{shots[0]["src"]}.webp',
                            ' data-z2o-viewer data-barba-prevent', VIEW_IMAGE)
    else:
        raise SystemExit(f"  ❌ '{item['slug']}' بلا وجهة: لا صفحة ولا لقطات")

    cov = item["cover"]
    # One consistent image/title/summary/link layout for every gallery entry.
    # Detailed metrics remain on the case page or in the full evidence viewer.
    sizes = "(max-width: 639px) 92vw, (max-width: 1023px) 44vw, 380px"
    cats = " ".join(item["categories"])
    fit = "contain"  # Preserve complete artwork, logos and dashboard labels.
    o = [f'{pad}<li class="z2o-card z2o-card--uniform" data-categories="{cats}">',
         f'{pad}   <article class="z2o-card-inner">',
         f'{pad}      <div class="z2o-card-media z2o-fit-{fit}">',
         f'{pad}         ' + img_tag(cov["src"], cov["w"], cov["h"], cov["alt"],
                                     fit, eager=eager, sizes=sizes),
         f'{pad}      </div>',
         f'{pad}      <div class="z2o-card-body">',
         f'{pad}         <p class="z2o-card-tag">{item["tag"]}</p>',
         f'{pad}         <h3 class="z2o-card-title">'
         f'<a class="z2o-card-link" href="{href}"{extra}>{item["title"]}</a></h3>',
         f'{pad}         <p class="z2o-card-summary">{item["summary"]}</p>',
         f'{pad}         <p class="z2o-card-cue" aria-hidden="true">{cue}</p>',
         f'{pad}      </div>']

    o += shots_block(item, f'{pad}      ')
    o += [f'{pad}   </article>', f'{pad}</li>']
    return "\n".join(o)


# ------------------------------------------------------------------- work
def render_work():
    cats = used_categories()
    counts = {k: sum(1 for i in ITEMS if k in i["categories"]) for k, _ in cats}
    o = []

    # فتات التنقّل
    o += ['            <nav class="z2o-breadcrumb" aria-label="Breadcrumb" data-scroll-section>',
          '               <div class="container medium">',
          '                  <ol class="z2o-breadcrumb-list">',
          '                     <li><a href="/">Home</a></li>',
          f'                     <li><span aria-current="page">{WORK_H1}</span></li>',
          '                  </ol>',
          '               </div>',
          '            </nav>']

    # مقدّمة قصيرة — الشبكة تبدأ قبل أن يضطرّ الزائر للتمرير مرّتين
    o += ['            <section class="section z2o-work-intro once-in" data-scroll-section>',
          '               <div class="container medium">',
          '                  <div class="row">',
          '                     <div class="flex-col fade-in animate">',
          f'                        <p class="z2o-work-lead">{WORK_LEAD}</p>',
          f'                        <p class="z2o-work-note">{WORK_NOTE}</p>',
          '                     </div>',
          '                  </div>',
          '               </div>',
          '            </section>']

    # المرشّحات والشبكة
    o += ['            <section class="section z2o-work-gallery once-in" data-scroll-section '
          'aria-labelledby="z2o-filter-heading">',
          '               <div class="container medium">',
          f'                  <h2 class="z2o-sr-only" id="z2o-filter-heading">{WORK_FILTER_HEADING}</h2>',
          # hidden حتى يشغّلها الجافاسكربت: بلا جافاسكربت تظهر المجموعة كاملة
          # ولا يرى الزائر أزراراً لا تفعل شيئاً.
          '                  <div class="z2o-filters" role="group" '
          'aria-labelledby="z2o-filter-heading" hidden data-z2o-filters>',
          '                     <button type="button" class="z2o-filter is-selected" '
          f'data-z2o-filter="all" aria-pressed="true">{WORK_ALL} '
          f'<span class="z2o-filter-count">{len(ITEMS)}</span></button>']
    for key, label in cats:
        o.append('                     <button type="button" class="z2o-filter" '
                 f'data-z2o-filter="{key}" aria-pressed="false">{label} '
                 f'<span class="z2o-filter-count">{counts[key]}</span></button>')
    o += ['                  </div>',
          '                  <p class="z2o-sr-only" role="status" aria-live="polite" '
          'data-z2o-filter-status></p>',
          '                  <ul class="z2o-gallery" data-z2o-gallery>']
    for n, item in enumerate(gallery()):
        o.append(card(item, "                     ", eager=(n == 0)))
    o += ['                  </ul>',
          strings_block("                  "),
          '                  <p class="z2o-video-library">',
          f'                     <a href="{VIDEO_LIBRARY_URL}" target="_blank" '
          f'rel="noopener">{VIDEO_LABEL}</a>',
          f'                     <span class="z2o-video-library-note">{VIDEO_NOTE}</span>',
          '                  </p>',
          '               </div>',
          '            </section>']

    # دعوة الختام — وجهة التواصل نفسها المستعملة في بقية الموقع
    o += ['            <section class="section z2o-work-cta once-in" data-scroll-section>',
          '               <div class="container medium">',
          '                  <div class="row">',
          '                     <div class="flex-col fade-in animate">',
          f'                        <h2 class="z2o-work-cta-title">{WORK_CTA_TITLE}</h2>',
          f'                        <p class="z2o-work-cta-body">{WORK_CTA_BODY}</p>',
          '                        <div class="btn-wrap theme-dark">',
          '                           <div class="btn btn-round">',
          f'                              <a href="{WHATSAPP_URL}" target="_blank" rel="noopener" '
          'class="btn-click magnetic" data-strength="100" data-strength-text="50">',
          '                                 <div class="btn-fill"></div>',
          '                                 <span class="btn-text">',
          f'                                    <span class="btn-text-inner">{WORK_CTA_LABEL}</span>',
          '                                 </span>',
          '                              </a>',
          '                           </div>',
          '                        </div>',
          '                     </div>',
          '                  </div>',
          '               </div>',
          '            </section>',
          '         </section>']
    return "\n".join(o) + "\n"


# ------------------------------------------------------------------ splice
def splice_work(html):
    html = html.replace("<h1><span>Our Work</span> &mdash; Brands Built in Riyadh</h1>",
                        f"<h1>{WORK_H1}</h1>")
    html = html.replace("<h1><span>Our Work</span> — Brands Built in Riyadh</h1>",
                        f"<h1>{WORK_H1}</h1>")
    start = html.find("</header>")
    if start < 0:
        raise SystemExit("  ❌ لا </header> في work/index.html")
    start += len("</header>")
    end = html.find('<div class="footer-rounded-div"')
    if end < start:
        raise SystemExit("  ❌ لا فوتر في work/index.html")
    end = html.rfind("\n", 0, end) + 1
    return html[:start] + "\n" + render_work() + html[end:]


def main():
    check = "--check" in sys.argv
    validate()
    drift = []
    for rel, fn in (("work/index.html", splice_work),):
        path = os.path.join(ROOT, rel)
        old = open(path, encoding="utf-8").read()
        new = fn(old)
        if old == new:
            print(f"  = {rel} بلا تغيير")
            continue
        if check:
            drift.append(rel)
            continue
        open(path, "w", encoding="utf-8").write(new)
        print(f"  ✅ {rel}  {len(new)/1024:.0f} KB")

    if check and drift:
        print(f"\n  ❌ المعرض قديم: {', '.join(drift)} — شغّل الأداة بلا --check.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
