#!/usr/bin/env python3
"""
ZERO 2 ONE — redirect builder
=============================

Reads tools/redirects.json and writes every layer of the redirect setup from
that one map, so they cannot drift apart:

  1. .htaccess ....... the RewriteRule block, between generated markers
                       (Apache / LiteSpeed — what Hostinger runs)
  2. _redirects ...... same rules in Netlify / Cloudflare Pages format, so the
                       redirects survive a move to either host
  3. stub pages ...... a real HTML file at each old path, carrying
                       <link rel="canonical"> + an instant meta refresh

Why the stubs matter
--------------------
.htaccess is a dotfile. Plenty of FTP clients hide dotfiles by default, so the
classic failure is uploading the site and silently leaving .htaccess behind —
at which point every old URL 404s and the rankings attached to it are gone.

The stubs remove that failure mode. When .htaccess is present, mod_rewrite
answers first with a real 301 and the stub is never served. When it is missing,
the stub answers instead: the visitor still lands on the right page and Google
still gets a canonical pointing at the new URL. Slightly weaker signal, but
never a 404, and never on any host.

Run `python3 tools/verify_deploy.py` after deploying to see which layer is
actually answering in production.

Usage:
    python3 tools/build_redirects.py
    python3 tools/build_redirects.py --check   # fail if anything is out of date
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, "tools", "redirects.json")
HTACCESS = os.path.join(ROOT, ".htaccess")
NETLIFY = os.path.join(ROOT, "_redirects")

BEGIN = "    # >>> BEGIN generated redirects — tools/build_redirects.py (do not edit by hand)"
END = "    # <<< END generated redirects"

STUB = """<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />
   <title>Moved — ZERO 2 ONE</title>
   <!-- This page only ever appears if the .htaccess 301 did not upload. It keeps
        the old URL from 404ing and still consolidates it onto the new one. -->
   <link rel="canonical" href="{base}{to}" />
   <meta http-equiv="refresh" content="0; url={to}" />
   <meta name="theme-color" content="#F9460E" />
   <style>
      html {{ background: #1C1D20; color: #FFF; font-family: system-ui, sans-serif; }}
      body {{ display: flex; min-height: 100vh; margin: 0; align-items: center; justify-content: center; }}
      main {{ text-align: center; padding: 2rem; }}
      a {{ color: #F9460E; }}
   </style>
</head>

<body>
   <main>
      <p>This page has moved.</p>
      <p><a href="{to}">Continue to {to}</a></p>
   </main>
   <script>location.replace({to_js});</script>
</body>

</html>
"""


def load():
    data = json.load(open(MAP, encoding="utf-8"))
    return data["base"].rstrip("/"), data["redirects"]


def htaccess_block(redirects):
    width = max(len(r["from"].lstrip("/").replace(".", "\\.")) for r in redirects) + 2
    lines = [BEGIN,
             "    # Source: tools/redirects.json — regenerate with tools/build_redirects.py",
             "    # These are permanent. Each one carries the ranking of a retired URL."]
    for r in redirects:
        pattern = "^" + r["from"].lstrip("/").replace(".", "\\.") + "$"
        lines.append(f"    RewriteRule {pattern:<{width + 2}} {r['to']:<38} [R=301,L]")
    lines.append(END)
    return "\n".join(lines)


def netlify_file(redirects):
    width = max(len(r["from"]) for r in redirects) + 2
    out = ["# Generated by tools/build_redirects.py from tools/redirects.json.",
           "# Netlify / Cloudflare Pages read this file; Apache hosts use .htaccess",
           "# instead. Both are generated from the same map, so they always agree.",
           ""]
    for r in redirects:
        out.append(f"{r['from']:<{width}} {r['to']:<38} 301")
    return "\n".join(out) + "\n"


def stub_path(from_path):
    rel = from_path.lstrip("/")
    if rel.endswith("/") or not rel.endswith(".html"):
        rel = rel.rstrip("/") + "/index.html"
    return os.path.join(ROOT, rel)


def write_all(check_only=False):
    base, redirects = load()
    stale = []

    # 1) .htaccess block
    current = open(HTACCESS, encoding="utf-8").read()
    block = htaccess_block(redirects)
    if BEGIN in current and END in current:
        head = current[: current.index(BEGIN)]
        tail = current[current.index(END) + len(END):]
        updated = head + block + tail
    else:
        raise SystemExit(
            f"markers not found in .htaccess — expected a line reading:\n{BEGIN}")
    if updated != current:
        stale.append(".htaccess")
        if not check_only:
            open(HTACCESS, "w", encoding="utf-8").write(updated)

    # 2) _redirects
    want = netlify_file(redirects)
    have = open(NETLIFY, encoding="utf-8").read() if os.path.isfile(NETLIFY) else None
    if have != want:
        stale.append("_redirects")
        if not check_only:
            open(NETLIFY, "w", encoding="utf-8").write(want)

    # 3) stub pages
    for r in redirects:
        path = stub_path(r["from"])
        want = STUB.format(base=base, to=r["to"], to_js=json.dumps(r["to"]))
        have = open(path, encoding="utf-8").read() if os.path.isfile(path) else None
        if have != want:
            stale.append(os.path.relpath(path, ROOT))
            if not check_only:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                open(path, "w", encoding="utf-8").write(want)

    if check_only:
        if stale:
            print("OUT OF DATE — run tools/build_redirects.py:")
            for s in stale:
                print("  ", s)
            return 1
        print(f"up to date — {len(redirects)} redirects, 3 layers in sync")
        return 0

    print(f"{len(redirects)} redirects written to 3 layers:")
    print(f"  .htaccess    RewriteRule block (Apache / LiteSpeed / Hostinger)")
    print(f"  _redirects   Netlify / Cloudflare Pages")
    print(f"  stub pages   {', '.join(os.path.relpath(stub_path(r['from']), ROOT) for r in redirects[:3])} …")
    if stale:
        print(f"\nupdated {len(stale)} file(s)")
    else:
        print("\nnothing changed — already in sync")
    return 0


if __name__ == "__main__":
    sys.exit(write_all(check_only="--check" in sys.argv))
